tokenizer: roberta-large
plm: roberta-large
lm_size: 1024
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
combined_action: True
max_sequence_length: 200
cached_dir: "cache/PREFERENCE_PPDPP/"
weight_decay: 0.01
learning_rate: 0.00005
num_warmup_steps: 3000
gradient_accumulation_steps: 1
num_train_epochs: 5
dropout: 0.1
max_grad_norm: 5
run_sft: false
run_rlt: true
run_online_eval: false
run_offline_eval: false
num_train_rl_epochs: 100
train_rl_batch_size: 32
sampled_times: 10
freeze_preference_backbone: true
num_train_preference_epochs: 5
preference_warmup_steps: 200
reward_hidden_size: 32
preference_batch_size: 8
num_train_ppo_epochs: 10
actor_warmup_steps: 200
critic_warmup_steps: 200