tokenizer: bert-base-cased
plm: bert-base-cased
lm_size: 768
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
max_sequence_length: 512
cached_dir: "cache/RTCP/"
weight_decay: 0.01
learning_rate: 0.00005
num_warmup_steps: 3000
gradient_accumulation_steps: 1
num_train_epochs: 5
dropout: 0.1
max_grad_norm: 5
run_sft: false
run_online_eval: true
run_offline_eval: false
ffn_size: 3072
n_layers: 6
n_heads: 8
fc_size: 128