tokenizer: facebook/bart-base
plm: facebook/bart-base
lm_size: 768
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
max_sequence_length: 512
max_target_length: 100
max_gen_length: 50
cached_dir: "cache/UNIMIND/"
weight_decay: 0.01
learning_rate: 0.00005
num_warmup_steps: 3150
gradient_accumulation_steps: 1
num_train_epochs: 5
num_finetune_epochs: 2
do_pretrain: true
do_finetune: true
dropout: 0.1
max_grad_norm: 5
run_sft: false
run_online_eval: true
run_offline_eval: false