name: "emotional_support"
log_dir: "logs/emotional_support/"
saved_dir: "checkpoints/emotional_support/"
n: 5
epsilon: 0.6
max_horizon: 10
objectives: [ "user_reward", "toxicity", "avg_turn" ]
model_type: "llama3"