dataset_name: inspired
train_data_path: data/rec_data/inspired/data/dialog_data/train.tsv
dev_data_path: data/rec_data/inspired/data/dialog_data/dev.tsv
test_data_path: data/rec_data/inspired/data/dialog_data/test.tsv
n_goals: 12
n_topics: 13330
log: true
save_goal_path: data/rec_data/inspired/data/dialog_data/goal.pkl
save_topic_path: data/rec_data/inspired/data/dialog_data/topic.pkl
save_dev_simulator_path: data/rec_data/inspired/data/dev_sim.pkl
save_test_simulator_path: data/rec_data/inspired/data/test_sim.pkl
save_action: false
load_action: true
save_train_convs: true
num_train_items: 368
num_dev_items: 42
num_test_items: 55
terminated_action: "Say goodbye"
max_horizon: 7